//crud notes 
export const GETALL = 'GET_ALL'
export const PERSONAL_NOTES = 'PERSONAL_NOTES'
export const FOLLOWED_NOTES = 'FOLLOWED_NOTES'
export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const FILTER = 'FILTER'
export const FILTER_TIMELINE = 'FILTER_TIMELINE'
export const CLEAN_NOTES = 'CLEAN_NOTES'
export const FOLLOW_NOTES_UPDATE = 'FOLLOW_NOTES_UPDATE'
// auth reducer
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const FOLLOW_USER_UPDATE = 'FOLLOW_USER_UPDATE'
// for errors
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
// for users
export const GET_USERS = 'GET_USERS'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS'