export  { default as Header} from './header/Header'
export  { default as Home} from './home/Home'
export  { default as Footer} from './footer/Footer'
export  { default as Notes} from './notes/Notes'
export  { default as Form} from './form/Form'
export  { default as Registration} from './registration/Registration'
export  { default as Signup} from './registration/Signup'
export  { default as Signin} from './registration/Signin'
